name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make clang libprotobuf23 libssl3
          version: 1.0

      - name: Configure
        run: ./scripts/Setup.sh

      - name: Build
        run: make
